# Generated by Django 5.2.12 on 2026-03-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., Bachelor of Engineering', max_length=100)),
                ('specialization', models.CharField(help_text='e.g., Electronics and Communication Engineering', max_length=100)),
                ('institution', models.CharField(help_text='e.g., Velammal Engineering College', max_length=200)),
                ('year_range', models.CharField(help_text='e.g., 2021 - 2025', max_length=50)),
                ('score_type', models.CharField(help_text='e.g., CGPA or Percentage', max_length=50)),
                ('score_value', models.CharField(help_text='e.g., 8.30 or 91.14%', max_length=50)),
                ('icon_class', models.CharField(help_text="e.g., 'fas fa-graduation-cap'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="FontAwesome icon class, e.g., 'fas fa-code'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mohan Kumar', max_length=100)),
                ('role', models.CharField(default='Full Stack Developer', max_length=100)),
                ('hero_description', models.TextField()),
                ('about_description', models.TextField()),
                ('resume_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="e.g., 'fas fa-car'", max_length=50)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text="e.g., 'fas fa-palette'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text="Emoji or short text icon, e.g., '🌐'", max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TechBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_badges', to='portfolio.project')),
            ],
        ),
    ]
