# Generated by Django 5.2.12 on 2026-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_interest_personalinfo_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='e.g., Software Engineer', max_length=150)),
                ('company', models.CharField(help_text='e.g., Google', max_length=200)),
                ('duration', models.CharField(help_text='e.g., Jun 2023 – Present', max_length=100)),
                ('description', models.TextField(help_text='Describe your responsibilities and achievements')),
                ('icon_class', models.CharField(default='fas fa-briefcase', help_text="e.g., 'fas fa-briefcase'", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
