# Generated by Django 5.2.12 on 2026-05-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='info',
            field=models.CharField(default='Experience with this technology', help_text='Short description for the flip card back', max_length=200),
        ),
    ]
