# Generated by Django 5.2.12 on 2026-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='info',
        ),
        migrations.AddField(
            model_name='skill',
            name='code_snippet',
            field=models.TextField(default="print('Hello World')", help_text='Small code snippet for the flip card back'),
        ),
    ]
