# Generated by Django 5.2.12 on 2026-05-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_skill_info_skill_code_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='resume_view_link',
            field=models.URLField(blank=True, help_text='Link for viewing resume in browser', null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Link for downloading resume', null=True),
        ),
    ]
